### ISSUE TITLE
felaktigt text (inte typos)

### ISSUE THREAD

**Issue by sinanaltaii** [csharpschool/AspNetCorePublisherWebAPI#1]
sida 51, 
"The interface will be accessible without creating instances of the class, 
preserving the data and any changes until the application is stopped"
 
tillhör rubriken  Creating the In-Memory Data Collections
interface bör vara class
Nu vet jag inte om det här tillhör typos, för att det man skapar är en class, eller menade du interface:t som man skapar senare i boken?

**Comment by csharpschool** [comment]
It should be: 
You won't have to create any other instances of the class, the data and any changes will be preserved until the application is stopped.
